-- MySQL Script generated by MySQL Workbench
-- Fri Feb 13 16:13:56 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema _honeycomb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `_honeycomb` ;

-- -----------------------------------------------------
-- Schema _honeycomb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `_honeycomb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `_honeycomb` ;

-- -----------------------------------------------------
-- Table `_honeycomb`.`_product_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_product_types` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_product_types` (
  `id` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(128) NULL,
  `proper_name` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_product` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `_product_style` VARCHAR(45) NULL,
  `_product_name` VARCHAR(256) NULL,
  `_description` LONGTEXT NULL,
  `_product_primary_type` INT NULL,
  `_year` VARCHAR(45) NULL,
  `_in_prod_cat` INT NULL DEFAULT 0,
  `_custom` INT NULL DEFAULT 0,
  `_active` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_product`),
  INDEX `_product_primary_type_idx` (`_product_primary_type` ASC),
  CONSTRAINT `_product_primary_type`
    FOREIGN KEY (`_product_primary_type`)
    REFERENCES `_honeycomb`.`_product_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_prod_attributes_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_prod_attributes_options` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_prod_attributes_options` (
  `id` INT NULL,
  `_attr_type` VARCHAR(45) NULL,
  `_attr_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'This is a table of attributes';


-- -----------------------------------------------------
-- Table `_honeycomb`.`_product_attr_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_product_attr_library` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_product_attr_library` (
  `id` INT NOT NULL DEFAULT 0,
  `_product_type` INT NULL,
  `_prod_attr_option` INT NULL,
  `name` VARCHAR(256) NULL,
  `val` VARCHAR(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `_product_type_idx` (`_product_type` ASC),
  INDEX `_prod_attr_option_idx` (`_prod_attr_option` ASC),
  CONSTRAINT `_product_type`
    FOREIGN KEY (`_product_type`)
    REFERENCES `_honeycomb`.`_product_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `_prod_attr_option`
    FOREIGN KEY (`_prod_attr_option`)
    REFERENCES `_honeycomb`.`_prod_attributes_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_prod_attrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_prod_attrs` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_prod_attrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_product_id` INT NULL,
  `_prod_attr_option` INT NULL,
  `_prod_option` INT NULL,
  `val` LONGTEXT NULL,
  `val_large` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`_product_id` ASC),
  INDEX `attr_id_idx` (`_prod_attr_option` ASC),
  INDEX `prod_option_idx` (`_prod_option` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`_product_id`)
    REFERENCES `_honeycomb`.`_product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `attr_id`
    FOREIGN KEY (`_prod_attr_option`)
    REFERENCES `_honeycomb`.`_prod_attributes_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prod_option`
    FOREIGN KEY (`_prod_option`)
    REFERENCES `_honeycomb`.`_product_attr_library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'This table contains product attributes.';


-- -----------------------------------------------------
-- Table `_honeycomb`.`_client_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_client_companies` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_client_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cust_type` VARCHAR(45) NULL DEFAULT NULL,
  `is_factory` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_clients_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_clients_contact` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_clients_contact` (
  `id` INT NULL DEFAULT 0,
  `company_id` INT NULL DEFAULT 0,
  `cust_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `company_id`
    FOREIGN KEY (`id`)
    REFERENCES `_honeycomb`.`_client_companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_cont_attrs_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_cont_attrs_types` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_cont_attrs_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'This table dictates what kinds of information can be added to the contacts.';


-- -----------------------------------------------------
-- Table `_honeycomb`.`_cont_attrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_cont_attrs` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_cont_attrs` (
  `cont_id` INT NULL,
  `type` INT NULL,
  `val` VARCHAR(45) NULL,
  `val_large_text` BLOB NULL,
  PRIMARY KEY (`cont_id`),
  INDEX `cont_attr_type_idx` (`type` ASC),
  CONSTRAINT `contact_id`
    FOREIGN KEY (`cont_id`)
    REFERENCES `_honeycomb`.`_clients_contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cont_attr_type`
    FOREIGN KEY (`type`)
    REFERENCES `_honeycomb`.`_cont_attrs_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_inventory` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `orig_product_id_idx` (`_product_id` ASC),
  CONSTRAINT `orig_product_id`
    FOREIGN KEY (`_product_id`)
    REFERENCES `_honeycomb`.`_product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_comp_attrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_comp_attrs` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_comp_attrs` (
  `comp_id` INT NULL,
  `type` INT NULL,
  `val` VARCHAR(45) NULL,
  `val_large_text` BLOB NULL,
  PRIMARY KEY (`comp_id`),
  INDEX `cont_attr_type_idx` (`type` ASC),
  CONSTRAINT `contact_id0`
    FOREIGN KEY (`comp_id`)
    REFERENCES `_honeycomb`.`_client_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cont_attr_type0`
    FOREIGN KEY (`type`)
    REFERENCES `_honeycomb`.`_cont_attrs_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_product_pricing_grid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_product_pricing_grid` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_product_pricing_grid` (
  `id` INT NOT NULL DEFAULT 0,
  `_product_id` INT NOT NULL DEFAULT 0,
  `ship_type` INT NOT NULL,
  `minimum_quantity` INT NOT NULL COMMENT '	',
  `price` INT NOT NULL,
  `ask_for_quote` INT NOT NULL DEFAULT 0,
  `public` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `prod_id_idx` (`_product_id` ASC),
  CONSTRAINT `prod_id`
    FOREIGN KEY (`_product_id`)
    REFERENCES `_honeycomb`.`_product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_orders` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_order` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `company_contact` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_ordered_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_ordered_items` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_ordered_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_order_id` INT NOT NULL,
  `_product_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `_order_id_idx` (`_order_id` ASC),
  INDEX `_product_id_idx` (`_product_id` ASC),
  CONSTRAINT `_order_id`
    FOREIGN KEY (`_order_id`)
    REFERENCES `_honeycomb`.`_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `_product_id`
    FOREIGN KEY (`_product_id`)
    REFERENCES `_honeycomb`.`_product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_honeycomb`.`_ordered_item_attrs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_honeycomb`.`_ordered_item_attrs` ;

CREATE TABLE IF NOT EXISTS `_honeycomb`.`_ordered_item_attrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `_ordered_item_id` INT NOT NULL,
  `item_attr` INT NULL,
  `val` LONGTEXT NULL,
  `val_large` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `ordered_item_id_idx` (`_ordered_item_id` ASC),
  INDEX `ordered_item_attr_idx` (`item_attr` ASC),
  CONSTRAINT `ordered_item_id`
    FOREIGN KEY (`_ordered_item_id`)
    REFERENCES `_honeycomb`.`_ordered_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ordered_item_attr`
    FOREIGN KEY (`item_attr`)
    REFERENCES `_honeycomb`.`_prod_attributes_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `_honeycomb` ;

-- -----------------------------------------------------
-- Placeholder table for view `_honeycomb`.`PRODUCT_CATALOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `_honeycomb`.`PRODUCT_CATALOG` (`id_product` INT, `_product_style` INT, `_product_name` INT, `_description` INT, `_product_primary_type` INT, `_year` INT, `_in_prod_cat` INT, `_custom` INT, `_active` INT);

-- -----------------------------------------------------
-- Placeholder table for view `_honeycomb`.`ACTIVE_PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `_honeycomb`.`ACTIVE_PRODUCTS` (`id_product` INT, `_product_style` INT, `_product_name` INT, `_description` INT, `_product_primary_type` INT, `_year` INT, `_in_prod_cat` INT, `_custom` INT, `_active` INT);

-- -----------------------------------------------------
-- View `_honeycomb`.`PRODUCT_CATALOG`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `_honeycomb`.`PRODUCT_CATALOG` ;
DROP TABLE IF EXISTS `_honeycomb`.`PRODUCT_CATALOG`;
USE `_honeycomb`;
CREATE  OR REPLACE VIEW `PRODUCT_CATALOG` AS SELECT * from _product where _in_prod_cat = '1' && _active = "1";

-- -----------------------------------------------------
-- View `_honeycomb`.`ACTIVE_PRODUCTS`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `_honeycomb`.`ACTIVE_PRODUCTS` ;
DROP TABLE IF EXISTS `_honeycomb`.`ACTIVE_PRODUCTS`;
USE `_honeycomb`;
CREATE  OR REPLACE VIEW `ACTIVE_PRODUCTS` AS SELECT * from _product where _active = "1";


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
